const provincesAndCities = {
  Pakistan: {
    "Khyber Pakhtunkhwa (KPK)": [
      "Abbottabad",
      "Bajaur",
      "Bannu",
      "Battagram",
      "Buner",
      "Charsadda",
      "Chitral",
      "Dera Ismail Khan",
      "Hangu",
      "Haripur",
      "Karak",
      "Kohat",
      "Kohistan",
      "Kurram",
      "Lakki Marwat",
      "Lower Dir",
      "Lower Kohistan",
      "Malakand",
      "Mansehra",
      "Mardan",
      "Mohmand",
      "North Waziristan",
      "Nowshera",
      "Orakzai",
      "Peshawar",
      "Shangla",
      "South Waziristan",
      "Swabi",
      "Swat",
      "Tank",
      "Torghar",
      "Upper Dir",
      "Upper Kohistan"
    ],
    Punjab: [
      "Attock",
      "Bahawalnagar",
      "Bahawalpur",
      "Bhakkar",
      "Chakwal",
      "Chiniot",
      "Dera Ghazi Khan",
      "Faisalabad",
      "Gujranwala",
      "Gujrat",
      "Hafizabad",
      "Jhang",
      "Jehlum",
      "Kasur",
      "Khanewal",
      "Khushab",
      "Lahore",
      "Layyah",
      "Lodhran",
      "Mandi Bahauddin",
      "Mianwali",
      "Multan",
      "Muzaffargarh",
      "Nankana Sahib",
      "Narowal",
      "Okara",
      "Pakpattan",
      "Rahim Yar Khan",
      "Rajanpur",
      "Rawalpindi",
      "Sahiwal",
      "Sargodha",
      "Sheikhupura",
      "Sialkot",
      "Toba Tek Singh",
      "Vehari"
    ],
    Sindh: [
      "Badin",
      "Dadu",
      "Ghotki",
      "Hyderabad",
      "Jacobabad",
      "Jamshoro",
      "Karachi",
      "Kashmore",
      "Khairpur",
      "Korangi",
      "Larkana",
      "Malir",
      "Matiari",
      "Mirpurkhas",
      "Naushahro Feroze",
      "Qambar Shahdadkot",
      "Sanghar",
      "Shaheed Benazirabad",
      "Shikarpur",
      "Sujawal",
      "Tharparkar",
      "Thatta",
      "Umerkot"
    ],
    Balochistan: [
      "Awaran",
      "Barkhan",
      "Bolan",
      "Chagai",
      "Dera Bugti",
      "Gwadar",
      "Harnai",
      "Jafarabad",
      "Jhal Magsi",
      "Kalat",
      "Kech",
      "Kharan",
      "Khuzdar",
      "Killa Abdullah",
      "Killa Saifullah",
      "Kohlu",
      "Lasbela",
      "Loralai",
      "Mastung",
      "Musakhel",
      "Naseerabad",
      "Nushki",
      "Panjgur",
      "Pishin",
      "Quetta",
      "Sherani",
      "Sibi",
      "Sohbatpur",
      "Washuk",
      "Zhob",
      "Ziarat"
    ],
    "Federal Capital Territory": ["Islamabad"],
    "Gilgit-Baltistan" : [
      "Astore",
      "Baltistan Division",
      "Diamer",
      "Ghanche",
      "Gilgit",
      "Hunza",
      "Kharmang",
      "Nagar",
      "Shigar",
      "Skardu"
    ],
    "Azad Kashmir" : [
      "Bagh",
      "Bhimber",
      "Hattian Bala",
      "Kotli",
      "Mirpur",
      "Muzaffarabad",
      "Neelum",
      "Poonch",
      "Sudhanoti"
    ]
  }
};

export default provincesAndCities;
